### ISSUE TITLE
Editor - Null error on all text deletion

### ISSUE THREAD

**Issue by DmitrySboychakov** [visual-space/visual-editor#46]
The following exception happen to me after I select all the text in editor and press backspace to delete it. 
Looks like it is struggle to collect style of the line, which was already deleted. 
```
======== Exception caught by services library ======================================================
The following _CastError was thrown while processing the key message handler:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      Line.collectStyle (package:visual_editor/documents/models/nodes/line.dart:379:28)
#1      Document.collectStyle (package:visual_editor/documents/models/document.dart:176:31)
#2      EditorController.getSelectionStyle (package:visual_editor/controller/services/editor-controller.dart:144:10)
#3      EditorController.replaceText (package:visual_editor/controller/services/editor-controller.dart:265:21)
#4      RawEditorStateSelectionDelegateMixin.textEditingValue= (package:visual_editor/editor/widgets/mixins/selection-delegate-mixin.dart:31:23)
#5      RawEditorStateSelectionDelegateMixin.userUpdateTextEditingValue (package:visual_editor/editor/widgets/mixins/selection-delegate-mixin.dart:161:5)
#6      RawEditorState._replaceText (package:visual_editor/editor/widgets/raw-editor.dart:919:5)
#7      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:534:39)
#8      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573:21)
#9      Actions.invoke.<anonymous closure> (package:flutter/src/widgets/actions.dart:872:48)
#10     Actions._visitActionsAncestors (package:flutter/src/widgets/actions.dart:653:18)
#11     Actions.invoke (package:flutter/src/widgets/actions.dart:866:30)
#12     DeleteTextAction.invoke (package:visual_editor/editor/services/actions/delete-text-action.dart:36:22)
#13     _OverridableContextAction.invokeDefaultAction (package:flutter/src/widgets/actions.dart:1696:28)
#14     _OverridableActionMixin.invoke (package:flutter/src/widgets/actions.dart:1559:9)
#15     ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:571:21)
#16     ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:755:38)
#17     _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:956:20)
#18     FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1687:32)
#19     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:828:34)
#20     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:875:15)
#21     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#22     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#23     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#24     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#25     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#29     _invoke2 (dart:ui/hooks.dart:189:10)
#30     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#31     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#32     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#33     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#34     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

```

**Comment by DmitrySboychakov** [comment]
Depends on  keepStyleOnNewLine: true in Controller

**Comment by adrian-moisa** [comment]
Hi @DmitrySboychakov. Thank you for submitting this issue. I've tried deleting all content from the demo quill. All seems fine. Can you elaborate on how to reproduce your situation? 

I'm currently the only active developer on the project. My current focus is the refactoring effort. I prioritise this to ensure that I have a far easier time at fixing such bugs as the one you reported. However it will take a bit of time until I manage to get to the bug you reported. Hope this is reasonable.

**Comment by adrian-moisa** [comment]
Apparently it is possible to reproduce if keepStyleOnNewLine is set on true.

**Comment by kairan77** [comment]
incidentally, this also relates to the quirkness of quill does not like empty string as input for empty document, you have to write something like {insert: '\n\ } as default in every instance when no data is returned from database, this is a bit cumbersome for new adopters since they have to wrap a check on their database returned data in every call, preferably this check could be internalized.

**Comment by adrian-moisa** [comment]
Yeah, I guess this wouldn't harm if we replace `''` with `{insert: '\n\ }`. But If I recall... I think there should be such a check already. I'll double check on it. What i know is that they use `\n` to start a new `TextSpan` widget in the multi child renderer (either TextLine or TextBlock). Though again, not high prio at the moment.

**Comment by adrian-moisa** [comment]
Can't reproduce
